name: ros2_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  built-and-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          python3-colcon-common-extensions \
          python3-vcstool \
          ros-humble-smach-ros \
          ros-humble-ament-cmake \
          ros-humble-launch-testing-ament-cmake \
          python3-pip
        pip3 uninstall -y em || true
        sudo rm -f /usr/local/bin/em.py
        pip3 install empy catkin_pkg colcon-common-extensions colcon-core
        
    - name: Setup ROS 2 workspace
      run: |
        mkdir -p ~/multirob_ws/src
        ln -s $GITHUB_WORKSPACE ~/multirob_ws/src
        cd ~/multirob_ws
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y --rosdistro humble


    - name: Build the workspace
      run: |
        source /opt/ros/humble/setup.bash
        cd ~/multirob_ws
        colcon build --packages-select multirobot --event-handlers console_direct+
        
    - name: Ensuring log directory exists
      run: mkdir -p ~/multirob_ws/log/latest_test

    - name: Run Tests
      run: |
        source /opt/ros/humble/setup.bash
        cd ~/multirob_ws
        colcon test --packages-select multirobot --event-handlers console_direct+
        colcon test-result --verbose
    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: colcon-logs
        path: ~/multirob_ws/log


